CREATE TABLE IF NOT EXISTS POST_OFFICE
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL UNIQUE,
    address VARCHAR(200) NOT NULL UNIQUE,
    index   VARCHAR(10)  NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTAL_DISPATCH
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_post_id INTEGER REFERENCES POST_OFFICE (id) NOT NULL,
    recipient_name      VARCHAR(100)                        NOT NULL,
    type                VARCHAR(50)                         NOT NULL,
    status              VARCHAR(50)                         NOT NULL
);

CREATE TABLE IF NOT EXISTS DISPATCH_HISTORY
(
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postal_dispatch_id          INTEGER REFERENCES POSTAL_DISPATCH (id) NOT NULL,
    current_destination_post_id INTEGER REFERENCES POST_OFFICE (id)     NOT NULL,
    status                      VARCHAR(50)                             NOT NULL,
    date_time                   TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);